export const ACTION_REGION_MODE = 'ACTION-REGION-MODE';
export const ACTION_ADD_REGION = 'ACTION-ADD-REGION';
export const ACTION_REMOVE_REGION = 'ACTION-REMOVE-REGION';
export const ACTION_RESET_REGION = 'ACTION-RESET-REGION';
export const ACTION_TOGGLE_SAVE_REGION = 'ACTION-TOGGLE-SAVE-REGION';
export const ACTION_SAVE_REGION = 'ACTION-SAVE-REGION';
export const ACTION_UPDATE_SELECTED_REGION = 'ACTION-UPDATE-SELECTED-REGION';
export const ACTION_TOGGLE_NODES = 'ACTION-TOGGLE-NODES';
